---
format: html
toc-depth: 2
---

- [Machine learning apps (Gradio)](https://huggingface.co/docs/transformers/pipeline_gradio)
- [Web server inference](https://huggingface.co/docs/transformers/pipeline_webserver)
- [Prompt engineering](https://huggingface.co/docs/transformers/tasks/prompting)
- [Text generation](https://huggingface.co/docs/transformers/llm_tutorial)
- [Tokenizers](https://huggingface.co/docs/transformers/fast_tokenizers)
- [Fine-tuning](https://huggingface.co/docs/transformers/training)







- **Semantic Search**
  - **Use Cases???**
  - Building Applications: [BERTopic](https://maartengr.github.io/BERTopic/index.html)
  - Selecting and Fine-tuning Models:
    - [SentenceTransformers: State-of-the-Art Text Embeddings](https://github.com/huggingface/sentence-transformers)
     - [Three (3) Model Types](https://www.sbert.net/#what-next)
    - [Fine-tune Embedding Models](https://unsloth.ai/docs/basics/embedding-finetuning)
     - Example: [EmbeddingGemma (300M) with Sentence Transformers](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/EmbeddingGemma_(300M).ipynb)

- **LLMs**
- [Datasets](https://huggingface.co/docs/hub/en/datasets-overview)
  - how to get splits
  - the viewer and how to use it
  - how to convert to DataFrame

- **Sharing demos** with [Gradio](https://www.gradio.app/guides/quickstart)

- **Docker** (required by LabelStudio and UnslothStudio)

- **Data Curation** with [LabelStudio](https://labelstud.io/guide) (alternative: [Argilla](https://huggingface.co/learn/llm-course/chapter10/1))
  1. First impression: [Template Gallery](https://labelstud.io/templates/)
  2. Setup: [Getting Started With Label Studio: A Step-By-Step Guide](https://labelstud.io/learn/getting-started-with-label-studio/) -- REQUIRES DOCKER
  3. [Introduction to Machine Learning with Label Studio](https://labelstud.io/blog/introduction-to-machine-learning-with-label-studio/)
  4. [How to Connect Hugging Face with Label Studio SDK](https://labelstud.io/tutorials/how_to_connect_hugging_face_with_label_studio_sdk)
    - HF → LS: Load datasets from Hugging Face into Label Studio for annotation
    - LS → HF: Export labeled data from Label Studio for model training
    - HF → LS: Connect Hugging Face models as ML backends for pre-annotations and active learning


References:

- [Official 🤗 Transformers Notebooks](https://huggingface.co/docs/transformers/notebooks)
- [Official 🦥 Unsloth Notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks)
- [Unsloth Studio](https://github.com/unslothai/unsloth): Run and train AI models with a unified local interface.

Easy Computer Vision:

- [Ultralytics Website](https://www.ultralytics.com/)
- [Ultralytics Platform](https://platform.ultralytics.com/): Train, Deploy, and Scale Ultralytics YOLO Models





## Framework Guide

Use `transformers` (HuggingFace): as the foundational, standard library for loading, training, and running models. You can boost fine-tuning speed and efficiency by using [`unsloth`](https://github.com/unslothai/unsloth). Both HuggingFace and Unsloth support deployment and inference.

Use [`sentence_transformers`](https://www.sbert.net/) specifically for state-of-the-art **embedding** and **reranker** models; used for semantic search, clustering, and classification.

Use [LabelStudio](https://labelstud.io/guide) (or [Argilla](https://huggingface.co/learn/llm-course/chapter10/1)) to curate data for training and fine-tuning.

Use `langchain`: to develop applications **powered by** language models.
