project:
  type: website
  title: "Applied AI Bootcamp"
  preview: 
    port: 4700
  output-dir: _site
  render: 
    - index.qmd
    - W1/
    - W2/
    - W3/
    - W4/
    - W5/

website:
  navbar:
    left:
      - href: W1/
        text: "Python"
      - href: W2/
        text: "DS"
      - href: W3/
        text: "ML"
      - href: W4/
        text: "Agentic"
      - href: W5/
        text: "DL"
  sidebar: 
    style: docked
    search: true

execute:
  # https://quarto.org/docs/computations/python.html#kernel-daemon
  daemon: 300
  
  # https://quarto.org/docs/computations/caching.html#jupyter-cache
  cache: true

  # https://quarto.org/docs/publishing/github-pages.html#freezing-computations
  freeze: auto

format:
  html:
    theme: [cosmo, assets/sdaia.scss, custom.scss]
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    anchor-sections: true
    html-math-method: katex
    mermaid-format: png
    
  revealjs:
    theme: [default, assets/sdaia.scss, custom.scss]
    
    mermaid:
      theme: default
    mermaid-format: png

    slide-number: c/t
    show-slide-number: all
    transition: slide
    background-transition: fade
    chalkboard: true
    progress: true
    history: false
    scrollable: true
    width: 1600
    height: 900
    center: false
    menu: 
      custom:
        - title: Links
          icon: '<i class="fas fa-link"></i>'
          content: >
            <ul class="slide-menu-items">
              <li class="slide-menu-item"><a href="/W1/">Python</a></li>
              <li class="slide-menu-item"><a href="/W2/">Applied Data Science</a></li>
              <li class="slide-menu-item"><a href="/W3/">Applied Machine Learning</a></li>
              <li class="slide-menu-item"><a href="/W4/">Agentic AI</a></li>
              <li class="slide-menu-item"><a href="/W5/">Applied Deep Learning</a></li>
            </ul>

number-depth: 1
lightbox: auto